psa-crypto/src/lib.rs, psa-crypto/src/operations/asym_signature.rs, psa-crypto/src/operations/key_management.rs, psa-crypto/src/types/key.rs, psa-crypto/src/types/status.rs
Also implements conversions between FFI types and Rust native types.
=> Split between Status and Error

.gitignore, psa-crypto-sys/Cargo.toml, psa-crypto-sys/README.md, psa-crypto-sys/src/lib.rs, psa-crypto/Cargo.toml, psa-crypto/README.md, psa-crypto/src/lib.rs, psa-crypto/src/types/algorithm.rs, psa-crypto/src/types/key.rs, psa-crypto/src/types/status.rs
This commit adds a feature to the `psa-crypto` crate to allow it to be
built without a library backing its API - this leaves only the type
system in place, with none of the callable methods.
The bindgen exports of `psa-crypto-sys` are also restricted to those
strictly necessary to the `psa-crypto` crate.
=> Improve interface of both crates

README.md, psa-crypto-sys/Cargo.toml, psa-crypto-sys/build.rs
This commit improves on the build mechanism for the sys crate. It moves
all temporary build material into OUT_DIR, including the mbedtls
config.h file and the build products of the library.
=> Improve build of psa-crypto-sys crate

psa-crypto-sys/src/c/shim.h, psa-crypto-sys/src/constants.rs, psa-crypto-sys/src/lib.rs
This allows this crate to be used to create a Rust Secure Element
driver.
=> Add Secure Element types definition

psa-crypto/Cargo.toml, psa-crypto/src/lib.rs, psa-crypto/src/types/status.rs
This commit adds a no-std feature that controls whether the crate
exposes any functionality that makes use of the standard library. The
feature is enabled by default.
In "std"-mode, the Display and Error traits are implemented on the
`Error` enum.
=> Add no-std feature; impl Display on Error

psa-crypto-sys/Cargo.toml, psa-crypto-sys/README.md, psa-crypto-sys/build.rs, psa-crypto-sys/src/c/shim.c, psa-crypto-sys/src/c/shim.h, psa-crypto-sys/src/lib.rs, psa-crypto/src/lib.rs, psa-crypto/src/types/status.rs
This commit:
* fixes a bug in build.rs where the shim library was not compiled when
dynamically linking
* add the psa_get_key_id function to the shim
* allow to access psa-crypto-sys from psa-crypto if compiling with Mbed
Crypto
* add a conversion from Error to psa_status_t to avoid going to Status
=> Add various improvements

psa-crypto-sys/src/lib.rs
Last commit before publishing! I checked `cargo publish --dry-run` and it works with this version of Mbed TLS 😄
=> Update Mbed TLS version and add new types

ci.sh, psa-crypto-sys/README.md, psa-crypto-sys/src/lib.rs
Last release of Mbed TLS included Nbed Crypto so we use that instead of
a commit number.
Also adds tests for dynamic linking on the CI.
=> Modify Mbed TLS version to most recent realease

psa-crypto-sys/src/c/shim.c, psa-crypto-sys/src/c/shim.h, psa-crypto-sys/src/constants.rs, psa-crypto-sys/src/lib.rs, psa-crypto-sys/src/shim_methods.rs, psa-crypto/src/lib.rs, psa-crypto/src/operations/asym_signature.rs, psa-crypto/src/operations/key_management.rs, psa-crypto/src/types/key.rs, psa-crypto/src/types/status.rs, psa-crypto/tests/mod.rs
Part of  [Parsec Issue #177](https://github.com/parallaxsecond/parsec/issues/177)
Includes #26 
Contains changes required to allow [Prasec](https://github.com/parallaxsecond/parsec) to use `psa-crypto` instead of binding directly to `mbedtls`.
=> Part of moving Parsec to use psa-crypto

ci.sh, psa-crypto-sys/src/c/shim.c, psa-crypto-sys/src/c/shim.h, psa-crypto-sys/src/shim_methods.rs, psa-crypto/src/operations/asym_signature.rs, psa-crypto/src/operations/key_management.rs, psa-crypto/src/types/key.rs
=> Added macro calls for sign output size and export key buffer size

psa-crypto/Cargo.toml, psa-crypto/src/types/algorithm.rs, psa-crypto/src/types/key.rs, psa-crypto/src/types/status.rs
This commit adds derivation of `Zeroize` for all types defined in the
`psa-crypto` crate.
=> Derive Zeroize for all types

ci.sh, psa-crypto-sys/README.md, psa-crypto-sys/build.rs
This is useful when this crate is used deep in the dependency tree.
=> Add an env var for static linking to Mbed Crypto

psa-crypto-sys/src/lib.rs, psa-crypto/Cargo.toml, psa-crypto/src/operations/key_management.rs, psa-crypto/tests/mod.rs
Added export_key() along with a simple test.
=> Added export_key

ci.sh, psa-crypto-sys/Cargo.toml, psa-crypto-sys/README.md, psa-crypto-sys/build.rs, psa-crypto-sys/src/constants.rs, psa-crypto-sys/src/lib.rs, psa-crypto/Cargo.toml, psa-crypto/README.md, psa-crypto/src/lib.rs, psa-crypto/src/types/algorithm.rs, psa-crypto/src/types/key.rs
For some use-cases, for example building a Secure Element driver, it is
only needed to have an abstraction over the PSA Crypto API include files
but not the operations. The new interface feature is made for that.
Fix #38
=> Add an interface feature only using include files

psa-crypto-sys/build.rs
We observe the following test failure for i686:
failures:
---- psa_crypto_binding::bindgen_test_layout_max_align_t stdout ----
thread 'psa_crypto_binding::bindgen_test_layout_max_align_t'
panicked at 'assertion failed: `(left == right)`
left: `16`,
right: `24`: Size of: max_align_t',
.../build/psa-crypto-sys-59266dd2c6e5c562/out/shim_bindings.rs:3:22153
This type isn't needed, so we can just blocklist it from bindgen.
=> Blocklist `max_align_t` in bindgen

psa-crypto/src/operations/key_derivation.rs, psa-crypto/src/types/key_derivation.rs, psa-crypto/tests/key_derivation.rs
Currently, key derivation does not properly support key agreement. This PR is a possible solution.
=> Refactor of key_derivation

psa-crypto/src/types/key.rs
=> Added helper methods for checking derivation policy flag

psa-crypto-sys/src/extras.rs, psa-crypto-sys/src/shim_methods.rs, psa-crypto/src/operations/aead.rs, psa-crypto/src/operations/key_agreement.rs, psa-crypto/src/types/key.rs, psa-crypto/tests/aead.rs
Added temporary implementation for getting output size of shared secret with EDCH algorithm (will be replaced with call to mbed TLS once it supports the macro).
Changed safety of some output size macro shim declarations as they have undefined return.
=> Added helper methods and changed safety of size macros

.github/workflows/ci.yml, psa-crypto/src/types/key_derivation.rs
Rust v1.46 has been released which has support for match statements in a const function, so I've updated this method to be const.
=> Changed key derivation convertor to const function

.github/workflows/nightly.yml, README.md, psa-crypto-sys/Cargo.toml, psa-crypto/Cargo.toml
=> Upgrade dependencies

psa-crypto-sys/src/c/shim.h, psa-crypto-sys/src/shim_methods.rs
The shim was not used and nothing to link against.
=> Remove shim_PSA_ALG_IS_FULL_LENGTH_MAC

psa-crypto-sys/Cargo.toml
The newest version needs clang-sys version 1.0.0 or above which causes
conflicts with other crates.
=> Lower the version of bindgen to avoid conflict

psa-crypto-sys/Cargo.toml, psa-crypto-sys/build.rs
When compiling without no features, just the abstractred types are in, without any dependency on the bindgen generated types. Removing the dependency of bindgen makes the compilation of this crate faster and easier in those cases.
=> Remove the bindgen dependency if not needed

psa-crypto/src/types/algorithm.rs
This commit adds a method to `AsymmetricSignature` to retrieve the hash
algorithm it is restricted to.
=> Add method to retrieve hash from AsymSign

psa-crypto-sys/build.rs, psa-crypto/src/lib.rs, psa-crypto/src/types/algorithm.rs, psa-crypto/src/types/key.rs
Also fixes some clippy/deprecated errors.
=> Implement Display on Algorithm

.github/workflows/ci.yml, ci.sh, psa-crypto-sys/README.md
Adds compilation of the whole workspace for two other targets. Also adds
some information in the README.md file.
=> Add cross-compilation tests

psa-crypto/src/types/key.rs
New functions for checking usage flags for PsaSignMessage and PsaVerifyMessage.
=> Add PsaSignMessage and PsaVerifyMessage usage flags functions

ci.sh, psa-crypto-sys/src/c/shim.c, psa-crypto-sys/src/c/shim.h, psa-crypto-sys/src/shim.rs, psa-crypto/src/types/key.rs, psa-crypto/tests/aead.rs, psa-crypto/tests/key_agreement.rs, psa-crypto/tests/key_derivation.rs
=> Move to Mbed TLS version 3.0.0

psa-crypto-sys/Cargo.toml
It builds fine with the newer version and other deps in the
parsec dependency chain already depend on 0.57.0.
Signed-off-by: Peter Robinson <pbrobinson@gmail.com>
=> psa-crypto-sys: bump bindgen to 0.57.0

.github/workflows/ci.yml, psa-crypto/Cargo.toml, psa-crypto/src/operations/asym_encryption.rs, psa-crypto/src/types/key.rs
This should put a stop to the nightly test failures.
=> Update from rsa 0.3.0 to 0.5.0.

psa-crypto-sys/build.rs
In building psa-crypto-sys we never execute the Mbed TLS tests, so
there is little point in building them. By not building them we save
CPU cycles and disc space and we make these crates a little more
portable as the tests use C library facilities that are not required
by the library.
=> build.rs: Build Mbed TLS with ENABLE_PROGRAMS=OFF, ENABLE_TESTING=OFF.

psa-crypto-sys/build.rs, psa-crypto-sys/src/c/shim.h
This probably makes no practical difference with the current version
of Mbed TLS and the current configuration but it might matter in the
future so this change could make psa-crypto-sys more maintainable.
At the top of "shim.h" we include the config file in the same way that
Mbed TLS .c files do, and in "build.rs" we add the output directory to
the include path and define MBEDTLS_CONFIG_FILE.
To make this work without the "operations" feature the code that
configures Mbed TLS is moved out of compile_mbed_crypto into a new
function, configure_mbed_crypto, that is called from script_interface
and script_operations.
Signed-off-by: Edmund Grimley Evans <edmund.grimley-evans@arm.com>
=> build.rs: Use generated config file with shim library headers.

psa-crypto/Cargo.toml
Updated to 1.4.3 not 1.5.* as the rsa crate has dependencies issue
Relates to #602
=> Bump zeroize version

psa-crypto-sys/build.rs, psa-crypto/src/lib.rs
This PR only removed `const_err` since it will be a hard error in future: https://github.com/rust-lang/rust/issues/71800
Signed-off-by: Marcus de Lima <marcus.lima@azion.com>
=> Update to remove const_err

ci.sh, psa-crypto-sys/Cargo.toml, psa-crypto/Cargo.toml, psa-crypto/src/lib.rs, psa-crypto/src/types/status.rs
Negative feature names are rejected by Clippy: they cause confusion when several crates depend on the same crate but with different sets of features.
The default set of features is changed but anyone who specifies `--no-default-features` or `default-features = false` will need to change what features they specify, so this is an incompatible change.
Also update toolchain from 1.58.1 to 1.60.0 in `.github/workflows/ci.yml` as `regex-syntax` v0.7.2 requires `rustc` 1.60.0 or newer.
=> Replace the "no-std" feature with a "std" feature

psa-crypto/Cargo.toml
Serde enables by default its std features, we do not want that.
=> Disable default-features on serde

.github/workflows/ci.yml, .github/workflows/nightly.yml
These are deprecated:
actions/checkout@v2, actions-rs/toolchain@v1, actions/setup-python@v2.
You can see a warning about it here, for example:
https://github.com/parallaxsecond/rust-psa-crypto/actions/runs/5937148892
=> Update GitHub workflows to use newer actions.

.github/workflows/ci.yml, psa-crypto-sys/Cargo.toml, psa-crypto-sys/README.md, psa-crypto-sys/build.rs, psa-crypto/Cargo.toml
A collision with another crate, even another crate that uses the same C library, should now be very unlikely, so the `links` line in `Cargo.toml` is removed. It should also be possible for a project to use multiple versions of this crate.
The libraries are now called `libpsa_crypto_0_10_0_shim.a` and `libpsa_crypto_0_10_0_mbedcrypto.a` and there is a new directory for them (`.../out/llib`) which does not contain any other libraries. All the globally defined symbols have the prefix `psa_crypto_0_10_0_`.
This relies on `bindgen::callbacks::ParseCallbacks::generated_name_override`, which was added in `bindgen` 0.64.0, which requires Rust 1.60.0. Currently we want `psa-crypto` to work with Rust 1.58.1. We could perhaps make this prefixing optional, enabled by a feature, but I don't think …
=> Add a prefix to the library names and to every global symbol

psa-crypto-sys/build.rs, psa-crypto/src/lib.rs
The nightly CI test "cargo +nightly udeps --workspace" failed with:
lint `private_in_public` has been removed: replaced with another
group of lints, see RFC
<https://rust-lang.github.io/rfcs/2145-type-privacy.html> for more
information
We leave the old lint for the benefit of old rustc versions and add some of the replacement lints, also adding #![allow(unknown_lints)].
This is an alternative to #119.
=> Add some lints and allow(unknown_lints).

psa-crypto-sys/build.rs, psa-crypto/src/lib.rs
It seems that we sometimes need this in addition to unknown_lints.
(I do not know why I didn't observe this problem yesterday when doing #120.)
=> Add allow(renamed_and_removed_lints).

CHANGELOG.md, Cargo.lock, psa-crypto-sys/Cargo.toml, psa-crypto/Cargo.toml
=> Update -sys crate version and add changelog

.github/workflows/ci.yml
The Rust compiler version according is incorrect in the job name 'build-1-60-0', it should be 'build-1-66-0'. However, to be more generic and for better maintainability:
* Change the job name to 'build-msrv'
* Replace occurrences of the Rust version with MSRV in all possible places.
=> ci.yml: Correct the Rust compiler version

psa-crypto-sys/build.rs
- ~Fix linking options against system provided mbedtls~ It was me using an ETOOOLD version of mbedtls. Just don't run configure on vendor'd mbedtls wqhen env vars set.
- Probably add a CI test for this, something like rm vendor directory, set build flags and ensure build works. Maybe even leer into open files of the process using the bindings and ensure its loaded mbedtls.
- Deduplicate parts of build.rs
=> Mbedtls fixes 0.12

psa-crypto-sys/build.rs
-  mbedtls: update to version 3.5.1
- build: support lib64 out directories
Could we get a release with this? (assuming no known bugs, worked on my systems :-p)
=> Update mbedtls to version 3.5.1

Cargo.lock, psa-crypto-sys/Cargo.toml, psa-crypto-sys/src/lib.rs, psa-crypto/src/operations/cipher.rs, psa-crypto/src/types/key_derivation.rs
- This is to go in line with other parallaxsecond repositories, in preparation for the next parsec release.
- 
- Solve other issues to fix nightly
=> Bump bindgen to 0.69.4
