parallaxsecond/rust-psa-crypto

psa-crypto-sys/build.rs

Pass parsec CI tests

---

README.md
psa-crypto-sys/Cargo.toml
psa-crypto-sys/build.rs

Re-run build if any file under psa-crypto-sys/vendor has changed

---

psa-crypto-sys/LICENSE
psa-crypto/LICENSE

Add license file to crates

---

psa-crypto-sys/src/lib.rs
psa-crypto/src/operations/other.rs

Hi guys -- first in a series of PRs for adding the `generate_random` function to Parsec. 🙂

Add support for `psa_generate_random`

---

psa-crypto/src/types/algorithm.rs

Added conversion helper methods

---

psa-crypto-sys/src/c/shim.c
psa-crypto-sys/src/c/shim.h
psa-crypto-sys/src/shim_methods.rs
psa-crypto/src/operations/aead.rs
psa-crypto/src/types/algorithm.rs
psa-crypto/src/types/key.rs

Added missing AEAD conversion and tag length method

---

.github/workflows/ci.yml

Fix indentation of the workflow

---

ci.sh
psa-crypto-sys/build.rs
psa-crypto/src/types/key_derivation.rs

Also add a way to spot a misure of the environment variables.

Fix the interface feature

---

.github/workflows/nightly.yml

The submodule folder was not being populated.

Fix nightly CI

---

psa-crypto/src/types/key_derivation.rs

Remove const for backwards compatibility

---

psa-crypto-sys/Cargo.toml
psa-crypto/Cargo.toml

Signed-off-by: Paul Howard <paul.howard@arm.com>

Bump both crates to 0.6.1

---

psa-crypto-sys/Cargo.toml
psa-crypto/Cargo.toml

Bump bindgen and crate versions

---

README.md
psa-crypto-sys/Cargo.toml
psa-crypto-sys/README.md
psa-crypto/Cargo.toml
psa-crypto/README.md

This commit bumps the version numbers of the two crates and applies some
minor, cosmetic changes.

Bump version and minor changes

---

README.md
psa-crypto-sys/build.rs

Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

Check for MbedTLS sources existance

---

psa-crypto/src/types/key.rs

Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

Add checks for keys sizes for psa_key_attributes_t convert

---

psa-crypto-sys/Cargo.toml
psa-crypto/Cargo.toml

Signed-off-by: Anton Antonov <Anton.Antonov@arm.com>

Bump psa-crypto and psa-crypto-sys versions

---

psa-crypto/src/lib.rs
psa-crypto/src/types/algorithm.rs
psa-crypto/src/types/key.rs
psa-crypto/src/types/status.rs

Fix issues reported by clippy

---

CHANGELOG.md
psa-crypto-sys/Cargo.toml
psa-crypto/Cargo.toml

Bumping psa-crypto and -sys versions

---

.github/workflows/ci.yml
psa-crypto-sys/Cargo.toml

Bump bindgen version

---

CHANGELOG.md
psa-crypto-sys/Cargo.toml
psa-crypto/Cargo.toml

Add changelog and update crate versions

---

CHANGELOG.md
Cargo.lock
psa-crypto/Cargo.toml

Update psa-crypto crate version and add changelog

---

psa-crypto-sys/README.md

Update README to specify prefix feature
